<a href="https://colab.research.google.com/github/aditivashivale11/nlp-sessions/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Libraries used Tensorflow and kera

In [5]:
!pip install tensorflow-gpu==2.10.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 578.0/578.0 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 78.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 62.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 110.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 438.7/438.7 kB 36.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 109.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 54.0 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 3.5.0
    Uninstalling keras-3.5.0:
      Successfully uninstalled keras-3.5.0
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  

In [6]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## vocabulary size
voc_size = 10000

**One-Hot Representation**

In [11]:
onehot_repr = [one_hot(words, voc_size)for words in sent]
print(onehot_repr)

[[867, 889, 7829, 6749], [867, 889, 7829, 3271], [867, 4649, 7829, 5182], [3677, 7147, 5158, 4314, 7074], [3677, 7147, 5158, 4314, 8067], [9756, 867, 5300, 7829, 9526], [6007, 3442, 3615, 4314]]


**Word Embedding Representation**

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [17]:
## pre-padding
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  867  889 7829 6749]
 [   0    0    0    0  867  889 7829 3271]
 [   0    0    0    0  867 4649 7829 5182]
 [   0    0    0 3677 7147 5158 4314 7074]
 [   0    0    0 3677 7147 5158 4314 8067]
 [   0    0    0 9756  867 5300 7829 9526]
 [   0    0    0    0 6007 3442 3615 4314]]


In [18]:
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam', 'mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
embedded_docs[0]

array([   0,    0,    0,    0,  867,  889, 7829, 6749], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 67ms/step


array([[-0.04246173, -0.03769623, -0.02114524, -0.00351321,  0.02587256,
        -0.01694406, -0.02158269, -0.0322715 ,  0.00411537,  0.03544719],
       [-0.04246173, -0.03769623, -0.02114524, -0.00351321,  0.02587256,
        -0.01694406, -0.02158269, -0.0322715 ,  0.00411537,  0.03544719],
       [-0.04246173, -0.03769623, -0.02114524, -0.00351321,  0.02587256,
        -0.01694406, -0.02158269, -0.0322715 ,  0.00411537,  0.03544719],
       [-0.04246173, -0.03769623, -0.02114524, -0.00351321,  0.02587256,
        -0.01694406, -0.02158269, -0.0322715 ,  0.00411537,  0.03544719],
       [ 0.04533596, -0.04599954, -0.04598931, -0.01257852, -0.02486931,
        -0.02233322, -0.01748972, -0.02890341,  0.03268435,  0.03347627],
       [-0.01333181,  0.0330374 , -0.00902902, -0.04756595, -0.01291931,
        -0.01275225, -0.01924024, -0.00728086, -0.02739395,  0.00232355],
       [ 0.03913425, -0.01936635,  0.00581615, -0.03025356,  0.04211301,
         0.01996988,  0.04078902,  0.02401792

In [23]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 33ms/step
[[[-0.04246173 -0.03769623 -0.02114524 -0.00351321  0.02587256
   -0.01694406 -0.02158269 -0.0322715   0.00411537  0.03544719]
  [-0.04246173 -0.03769623 -0.02114524 -0.00351321  0.02587256
   -0.01694406 -0.02158269 -0.0322715   0.00411537  0.03544719]
  [-0.04246173 -0.03769623 -0.02114524 -0.00351321  0.02587256
   -0.01694406 -0.02158269 -0.0322715   0.00411537  0.03544719]
  [-0.04246173 -0.03769623 -0.02114524 -0.00351321  0.02587256
   -0.01694406 -0.02158269 -0.0322715   0.00411537  0.03544719]
  [ 0.04533596 -0.04599954 -0.04598931 -0.01257852 -0.02486931
   -0.02233322 -0.01748972 -0.02890341  0.03268435  0.03347627]
  [-0.01333181  0.0330374  -0.00902902 -0.04756595 -0.01291931
   -0.01275225 -0.01924024 -0.00728086 -0.02739395  0.00232355]
  [ 0.03913425 -0.01936635  0.00581615 -0.03025356  0.04211301
    0.01996988  0.04078902  0.02401792 -0.01395752 -0.01649178]
  [ 0.00920218  0.01630146 -0.04081953 -0.02802962 -0.03795

In [24]:
### Assignment

sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [25]:
sent1

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [28]:
## vocabulary size
voc_size = 5000

In [29]:
onehot_repr1 = [one_hot(words,voc_size)for words in sent]
print(onehot_repr1)

[[951, 1095, 563, 3971], [951, 1095, 563, 965], [951, 2164, 563, 638], [1943, 1152, 174, 2964, 2477], [1943, 1152, 174, 2964, 1348], [630, 951, 878, 563, 1746], [649, 722, 2707, 2964]]


In [30]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [31]:
import numpy as np

In [32]:
sent_length=10
embedded_docs1=pad_sequences(onehot_repr1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[   0    0    0    0    0    0  951 1095  563 3971]
 [   0    0    0    0    0    0  951 1095  563  965]
 [   0    0    0    0    0    0  951 2164  563  638]
 [   0    0    0    0    0 1943 1152  174 2964 2477]
 [   0    0    0    0    0 1943 1152  174 2964 1348]
 [   0    0    0    0    0  630  951  878  563 1746]
 [   0    0    0    0    0    0  649  722 2707 2964]]


In [33]:
dim=10

In [34]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [36]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            50000     
                                                                 
Total params: 50,000
Trainable params: 50,000
Non-trainable params: 0
_________________________________________________________________


In [37]:
print(model.predict(embedded_docs1))

1/1 [==============================] - 0s 38ms/step
[[[ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.0278947   0.03872026 -0.00589031  0.00571404 -0.01949387
    0.00929886 -0.00017401  0.04171706 -0.00448577  0.02367464]
  [ 0.02696211 -0.00918621 -0.04543326 -0.02420766 -0.04886384
    0.00342915  0.01754621 -0.02890314 -0.04962314 -0.014431  ]
  [ 0.04793025 -0.00680728  0.04893715 -0.01515356  0.02483